apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  # Replace ARGOCD_SERVER with your ArgoCD server name (see https://medium.com/dzerolabs/installing-ambassador-argocd-and-tekton-on-kubernetes-540aacc983b9)
  ARGOCD_SERVER: 20.24.241.73
  ARGOCD_APPLICATION_NAME: 2048-game-app
  ARGOCD_APPLICATION_REVISION: HEAD

